EXMPLE  START   1000
.
.       ADDING TWO NUMBERS FIRST AND SECOND
.       THEN STORING THE RESULT IN ANSWER
.
        LDA     FIRST
        ADD     SECOND
        STA     ANSWER
FIRST   WORD    10
SECOND  WORD    15
ANSWER  RESW    1
        END     EXMPLE
